#This is a modified makefile intended to be used with clion

#===============Overrides===============#
#Override certain variables since we are not in the build directory
override ROOT_DIR := ..
override BUILD_DIR := $(ROOT_DIR)/Build

#Import original makefile with overriden variables
include $(BUILD_DIR)/makefile
